CREATE MEMORY TABLE if not exists "USER_DETAIL"
(
    "USER_ID"    int NOT NULL,
    "FIRST_NAME" CHARACTER VARYING(50),
    "LAST_NAME"  CHARACTER VARYING(50),
    "LOGIN"      CHARACTER VARYING(50)
);